// Code generated by xsdgen. DO NOT EDIT.

package vendor

import (
	"encoding/xml"
	"time"
)

type Anon1 struct {
	Date time.Time `xml:"Date,attr"`
	Time time.Time `xml:"Time,attr"`
}

func (t *Anon1) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T Anon1
	var layout struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	layout.T = (*T)(t)
	layout.Date = (*xsdDate)(&layout.T.Date)
	layout.Time = (*xsdTime)(&layout.T.Time)
	return e.EncodeElement(layout, start)
}
func (t *Anon1) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Anon1
	var overlay struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	overlay.T = (*T)(t)
	overlay.Date = (*xsdDate)(&overlay.T.Date)
	overlay.Time = (*xsdTime)(&overlay.T.Time)
	return d.DecodeElement(&overlay, &start)
}

type Anon2 struct {
	PostListItem   []PostListItem `xml:"PostListSchema_O PostListItem"`
	SequenceNumber int            `xml:"SequenceNumber,attr"`
	HotelId        string         `xml:"HotelId,attr"`
	PaymentMethod  string         `xml:"PaymentMethod,attr"`
	RevenueCenter  int            `xml:"RevenueCenter,attr,omitempty"`
	WaiterId       string         `xml:"WaiterId,attr,omitempty"`
	WorkstationId  string         `xml:"WorkstationId,attr"`
	Date           time.Time      `xml:"Date,attr"`
	Time           time.Time      `xml:"Time,attr"`
}

func (t *Anon2) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T Anon2
	var layout struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	layout.T = (*T)(t)
	layout.Date = (*xsdDate)(&layout.T.Date)
	layout.Time = (*xsdTime)(&layout.T.Time)
	return e.EncodeElement(layout, start)
}
func (t *Anon2) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Anon2
	var overlay struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	overlay.T = (*T)(t)
	overlay.Date = (*xsdDate)(&overlay.T.Date)
	overlay.Time = (*xsdTime)(&overlay.T.Time)
	return d.DecodeElement(&overlay, &start)
}

type LinkAlive struct {
	Date time.Time `xml:"Date,attr"`
	Time time.Time `xml:"Time,attr"`
}

func (t *LinkAlive) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T LinkAlive
	var layout struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	layout.T = (*T)(t)
	layout.Date = (*xsdDate)(&layout.T.Date)
	layout.Time = (*xsdTime)(&layout.T.Time)
	return e.EncodeElement(layout, start)
}
func (t *LinkAlive) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T LinkAlive
	var overlay struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	overlay.T = (*T)(t)
	overlay.Date = (*xsdDate)(&overlay.T.Date)
	overlay.Time = (*xsdTime)(&overlay.T.Time)
	return d.DecodeElement(&overlay, &start)
}

type LinkDescription struct {
	Date   time.Time `xml:"Date,attr"`
	Time   time.Time `xml:"Time,attr"`
	VerNum string    `xml:"VerNum,attr"`
}

func (t *LinkDescription) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T LinkDescription
	var layout struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	layout.T = (*T)(t)
	layout.Date = (*xsdDate)(&layout.T.Date)
	layout.Time = (*xsdTime)(&layout.T.Time)
	return e.EncodeElement(layout, start)
}
func (t *LinkDescription) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T LinkDescription
	var overlay struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	overlay.T = (*T)(t)
	overlay.Date = (*xsdDate)(&overlay.T.Date)
	overlay.Time = (*xsdTime)(&overlay.T.Time)
	return d.DecodeElement(&overlay, &start)
}

type LinkStart struct {
	Date time.Time `xml:"Date,attr"`
	Time time.Time `xml:"Time,attr"`
}

func (t *LinkStart) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T LinkStart
	var layout struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	layout.T = (*T)(t)
	layout.Date = (*xsdDate)(&layout.T.Date)
	layout.Time = (*xsdTime)(&layout.T.Time)
	return e.EncodeElement(layout, start)
}
func (t *LinkStart) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T LinkStart
	var overlay struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	overlay.T = (*T)(t)
	overlay.Date = (*xsdDate)(&overlay.T.Date)
	overlay.Time = (*xsdTime)(&overlay.T.Time)
	return d.DecodeElement(&overlay, &start)
}

type PostAnswer struct {
	RoomNumber     string    `xml:"RoomNumber,attr,omitempty"`
	ReservationId  int       `xml:"ReservationId,attr,omitempty"`
	LastName       string    `xml:"LastName,attr,omitempty"`
	AnswerStatus   string    `xml:"AnswerStatus,attr"`
	ResponseText   string    `xml:"ResponseText,attr"`
	CheckNumber    int       `xml:"CheckNumber,attr,omitempty"`
	SequenceNumber int       `xml:"SequenceNumber,attr"`
	HotelId        int       `xml:"HotelId,attr"`
	Date           time.Time `xml:"Date,attr"`
	Time           time.Time `xml:"Time,attr"`
	PaymentMethod  string    `xml:"PaymentMethod,attr"`
	RevenueCenter  int       `xml:"RevenueCenter,attr"`
	WaiterId       string    `xml:"WaiterId,attr,omitempty"`
	WorkstationId  string    `xml:"WorkstationId,attr"`
}

func (t *PostAnswer) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T PostAnswer
	var layout struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	layout.T = (*T)(t)
	layout.Date = (*xsdDate)(&layout.T.Date)
	layout.Time = (*xsdTime)(&layout.T.Time)
	return e.EncodeElement(layout, start)
}
func (t *PostAnswer) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T PostAnswer
	var overlay struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	overlay.T = (*T)(t)
	overlay.Date = (*xsdDate)(&overlay.T.Date)
	overlay.Time = (*xsdTime)(&overlay.T.Time)
	return d.DecodeElement(&overlay, &start)
}

type PostInquiry struct {
	InquiryInformation     string    `xml:"InquiryInformation,attr"`
	MaximumReturnedMatches int       `xml:"MaximumReturnedMatches,attr,omitempty"`
	SequenceNumber         int       `xml:"SequenceNumber,attr"`
	RequestType            int       `xml:"RequestType,attr"`
	PaymentMethod          string    `xml:"PaymentMethod,attr"`
	Date                   time.Time `xml:"Date,attr"`
	Time                   time.Time `xml:"Time,attr"`
	RevenueCenter          int       `xml:"RevenueCenter,attr,omitempty"`
	WaiterId               string    `xml:"WaiterId,attr,omitempty"`
	WorkstationId          string    `xml:"WorkstationId,attr"`
}

func (t *PostInquiry) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T PostInquiry
	var layout struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	layout.T = (*T)(t)
	layout.Date = (*xsdDate)(&layout.T.Date)
	layout.Time = (*xsdTime)(&layout.T.Time)
	return e.EncodeElement(layout, start)
}
func (t *PostInquiry) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T PostInquiry
	var overlay struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	overlay.T = (*T)(t)
	overlay.Date = (*xsdDate)(&overlay.T.Date)
	overlay.Time = (*xsdTime)(&overlay.T.Time)
	return d.DecodeElement(&overlay, &start)
}

type PostList struct {
	PostListItem   []PostListItem `xml:"PostListSchema_O PostListItem"`
	SequenceNumber int            `xml:"SequenceNumber,attr"`
	HotelId        string         `xml:"HotelId,attr"`
	PaymentMethod  string         `xml:"PaymentMethod,attr"`
	RevenueCenter  int            `xml:"RevenueCenter,attr,omitempty"`
	WaiterId       string         `xml:"WaiterId,attr,omitempty"`
	WorkstationId  string         `xml:"WorkstationId,attr"`
	Date           time.Time      `xml:"Date,attr"`
	Time           time.Time      `xml:"Time,attr"`
}

func (t *PostList) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T PostList
	var layout struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	layout.T = (*T)(t)
	layout.Date = (*xsdDate)(&layout.T.Date)
	layout.Time = (*xsdTime)(&layout.T.Time)
	return e.EncodeElement(layout, start)
}
func (t *PostList) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T PostList
	var overlay struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	overlay.T = (*T)(t)
	overlay.Date = (*xsdDate)(&overlay.T.Date)
	overlay.Time = (*xsdTime)(&overlay.T.Time)
	return d.DecodeElement(&overlay, &start)
}

type PostListItem struct {
	RoomNumber    string  `xml:"RoomNumber,attr"`
	ReservationId int     `xml:"ReservationId,attr"`
	LastName      string  `xml:"LastName,attr"`
	Vip           string  `xml:"Vip,attr,omitempty"`
	PaymentMethod string  `xml:"PaymentMethod,attr,omitempty"`
	NoPost        string  `xml:"NoPost,attr"`
	CreditLimit   float64 `xml:"CreditLimit,attr"`
	ProfileId     int     `xml:"ProfileId,attr"`
	HotelId       int     `xml:"HotelId,attr"`
	FirstName     string  `xml:"FirstName,attr,omitempty"`
	Title         string  `xml:"Title,attr,omitempty"`
	Reference1    string  `xml:"Reference1,attr,omitempty"`
	Reference2    string  `xml:"Reference2,attr,omitempty"`
	Reference3    string  `xml:"Reference3,attr,omitempty"`
	Reference4    string  `xml:"Reference4,attr,omitempty"`
	Reference5    string  `xml:"Reference5,attr,omitempty"`
	Reference6    string  `xml:"Reference6,attr,omitempty"`
	Reference7    string  `xml:"Reference7,attr,omitempty"`
	Reference8    string  `xml:"Reference8,attr,omitempty"`
	Reference9    string  `xml:"Reference9,attr,omitempty"`
	Reference10   string  `xml:"Reference10,attr,omitempty"`
}

type PostRequest struct {
	RoomNumber          string    `xml:"RoomNumber,attr"`
	ReservationId       int       `xml:"ReservationId,attr"`
	LastName            string    `xml:"LastName,attr"`
	HotelId             int       `xml:"HotelId,attr"`
	RequestType         int       `xml:"RequestType,attr"`
	InquiryInformation  string    `xml:"InquiryInformation,attr"`
	MatchfromPostList   int       `xml:"MatchfromPostList,attr"`
	SequenceNumber      int       `xml:"SequenceNumber,attr"`
	TotalAmount         int       `xml:"TotalAmount,attr"`
	CreditlimitOverride string    `xml:"CreditlimitOverride,attr,omitempty"`
	PostingDescription  string    `xml:"PostingDescription,attr,omitempty"`
	PaymentMethod       string    `xml:"PaymentMethod,attr"`
	Covers              int       `xml:"Covers,attr,omitempty"`
	RevenueCenter       int       `xml:"RevenueCenter,attr,omitempty"`
	ServingTime         int       `xml:"ServingTime,attr,omitempty"`
	CheckNumber         int       `xml:"CheckNumber,attr"`
	Subtotal1           int       `xml:"Subtotal1,attr,omitempty"`
	Subtotal2           int       `xml:"Subtotal2,attr,omitempty"`
	Subtotal3           int       `xml:"Subtotal3,attr,omitempty"`
	Subtotal4           int       `xml:"Subtotal4,attr,omitempty"`
	Subtotal5           int       `xml:"Subtotal5,attr,omitempty"`
	Subtotal6           int       `xml:"Subtotal6,attr,omitempty"`
	Subtotal7           int       `xml:"Subtotal7,attr,omitempty"`
	Subtotal8           int       `xml:"Subtotal8,attr,omitempty"`
	Subtotal9           int       `xml:"Subtotal9,attr,omitempty"`
	Subtotal10          int       `xml:"Subtotal10,attr,omitempty"`
	Subtotal11          int       `xml:"Subtotal11,attr,omitempty"`
	Subtotal12          int       `xml:"Subtotal12,attr,omitempty"`
	Subtotal13          int       `xml:"Subtotal13,attr,omitempty"`
	Subtotal14          int       `xml:"Subtotal14,attr,omitempty"`
	Subtotal15          int       `xml:"Subtotal15,attr,omitempty"`
	Subtotal16          int       `xml:"Subtotal16,attr,omitempty"`
	Discount1           int       `xml:"Discount1,attr,omitempty"`
	Discount2           int       `xml:"Discount2,attr,omitempty"`
	Discount3           int       `xml:"Discount3,attr,omitempty"`
	Discount4           int       `xml:"Discount4,attr,omitempty"`
	Discount5           int       `xml:"Discount5,attr,omitempty"`
	Discount6           int       `xml:"Discount6,attr,omitempty"`
	Discount7           int       `xml:"Discount7,attr,omitempty"`
	Discount8           int       `xml:"Discount8,attr,omitempty"`
	Discount9           int       `xml:"Discount9,attr,omitempty"`
	Discount10          int       `xml:"Discount10,attr,omitempty"`
	Discount11          int       `xml:"Discount11,attr,omitempty"`
	Discount12          int       `xml:"Discount12,attr,omitempty"`
	Discount13          int       `xml:"Discount13,attr,omitempty"`
	Discount14          int       `xml:"Discount14,attr,omitempty"`
	Discount15          int       `xml:"Discount15,attr,omitempty"`
	Discount16          int       `xml:"Discount16,attr,omitempty"`
	Tip                 int       `xml:"Tip,attr,omitempty"`
	ServiceCharge1      int       `xml:"ServiceCharge1,attr,omitempty"`
	ServiceCharge2      int       `xml:"ServiceCharge2,attr,omitempty"`
	ServiceCharge3      int       `xml:"ServiceCharge3,attr,omitempty"`
	ServiceCharge4      int       `xml:"ServiceCharge4,attr,omitempty"`
	ServiceCharge5      int       `xml:"ServiceCharge5,attr,omitempty"`
	ServiceCharge6      int       `xml:"ServiceCharge6,attr,omitempty"`
	ServiceCharge7      int       `xml:"ServiceCharge7,attr,omitempty"`
	ServiceCharge8      int       `xml:"ServiceCharge8,attr,omitempty"`
	ServiceCharge9      int       `xml:"ServiceCharge9,attr,omitempty"`
	ServiceCharge10     int       `xml:"ServiceCharge10,attr,omitempty"`
	ServiceCharge11     int       `xml:"ServiceCharge11,attr,omitempty"`
	ServiceCharge12     int       `xml:"ServiceCharge12,attr,omitempty"`
	ServiceCharge13     int       `xml:"ServiceCharge13,attr,omitempty"`
	ServiceCharge14     int       `xml:"ServiceCharge14,attr,omitempty"`
	ServiceCharge15     int       `xml:"ServiceCharge15,attr,omitempty"`
	ServiceCharge16     int       `xml:"ServiceCharge16,attr,omitempty"`
	Tax1                int       `xml:"Tax1,attr,omitempty"`
	Tax2                int       `xml:"Tax2,attr,omitempty"`
	Tax3                int       `xml:"Tax3,attr,omitempty"`
	Tax4                int       `xml:"Tax4,attr,omitempty"`
	Tax5                int       `xml:"Tax5,attr,omitempty"`
	Tax6                int       `xml:"Tax6,attr,omitempty"`
	Tax7                int       `xml:"Tax7,attr,omitempty"`
	Tax8                int       `xml:"Tax8,attr,omitempty"`
	Tax9                int       `xml:"Tax9,attr,omitempty"`
	Tax10               int       `xml:"Tax10,attr,omitempty"`
	Tax11               int       `xml:"Tax11,attr,omitempty"`
	Tax12               int       `xml:"Tax12,attr,omitempty"`
	Tax13               int       `xml:"Tax13,attr,omitempty"`
	Tax14               int       `xml:"Tax14,attr,omitempty"`
	Tax15               int       `xml:"Tax15,attr,omitempty"`
	Tax16               int       `xml:"Tax16,attr,omitempty"`
	Date                time.Time `xml:"Date,attr"`
	Time                time.Time `xml:"Time,attr"`
	WaiterId            string    `xml:"WaiterId,attr,omitempty"`
	WorkstationId       string    `xml:"WorkstationId,attr"`
}

func (t *PostRequest) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T PostRequest
	var layout struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	layout.T = (*T)(t)
	layout.Date = (*xsdDate)(&layout.T.Date)
	layout.Time = (*xsdTime)(&layout.T.Time)
	return e.EncodeElement(layout, start)
}
func (t *PostRequest) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T PostRequest
	var overlay struct {
		*T
		Date *xsdDate `xml:"Date,attr"`
		Time *xsdTime `xml:"Time,attr"`
	}
	overlay.T = (*T)(t)
	overlay.Date = (*xsdDate)(&overlay.T.Date)
	overlay.Time = (*xsdTime)(&overlay.T.Time)
	return d.DecodeElement(&overlay, &start)
}
