package saflok6000

import (
	"fmt"
)

var (
	grc03 = map[int]map[int]string{
		1:   {0: "PMS INTERFACE REQUESTED UNAVAILABLE TX. CONTACT PMS COMPANY."},
		2:   {0: "THE KEY LEVEL SELECTED IS NOT RELEVANT FOR THIS TX."},
		25:  {0: "SAFLOK ENI CORE & TX SOFTWARE IS INCOMPATIBLE. CONTACT SAFLOK."},
		26:  {0: "PMS INTERFACE REQUESTED AN INVALID TRANSACTION. CONTACT PMS COMPANY."},
		27:  {0: "PMS INTERFACE SENT PASSWORD < 3 CHARACTERS. CONTACT PMS COMPANY."},
		30:  {0: "YOUR SAFLOK PASSWORD IS INVALID. MUST CHANGE TO PMS PASSWORD (TX 116)"},
		31:  {0: "YOU ARE NOT AUTHORIZED IN SAFLOK TO DO THIS TX. MUST 1ST BE GIVEN AUTH (TX 116)"},
		32:  {0: "SAFLOK MAIN COMPUTER IS MISSING REQUIRED DATA FILES. CONTACT SAFLOK."},
		39:  {0: "KEY # nnnnn LEVEL yy DOES NOT EXIST. CONTACT SAFLOK TO ADD."},
		45:  {0: "SAFLOK MAIN COMPUTER IS MISSING REQ'D KEY FILES. CONTACT SAFLOK."},
		47:  {0: "SAFLOK COMPUTER IS ARCHIVING OR REPLACING FILES. MUST WAIT TILL DONE."},
		50:  {0: "KEY # nnnnn, LV yy IS CURRENTLY BEING ACCESSED BY ANOTHER TERMINAL."},
		51:  {0: "KEY # nnnnn, LV yy IS INCORRECTLY DESIGNATED AS FAILSAFE. CONTACT SAFLOK."},
		52:  {0: "YOU ARE NOT AUTHORIZED IN SAFLOK TO MAKE THIS KEY # nnnnn, LV yy."},
		100: {0: "PMS INTERFACE'S MESSAGE FORMAT IS INCORRECT. CONTACT PMS COMPANY."},
		101: {0: "PMS INTERFACE USED AN INVALID PMS TERMINAL/REQUEST #. CONTACT PMS COMPANY."},
		102: {0: "THE KEY LEVEL MUST BE BETWEEN 1 &4.CHANGE & RE-REQUEST."},
		103: {0: "KEY # nnnnn CONTAINS INVALID CHARACTERS. RE-ENTER KEY # & RE-REQUEST."},
		104: {0: "KEY # CANNOT BE NULL. RE-ENTER KEY # & RE-REQUEST."},
		107: {0: "PMS INTERFACE REQUESTED AN INVALID DATE. CONTACT PMS COMPANY."},
		108: {0: "PMS INTERFACE REQUESTED AN INVALID TIME. CONTACT PMS COMPANY."},
		109: {0: "THE ENCODER STATION MUST BE BETWEEN 1 & 60. CHANGE & RE-REQUEST"},
		110: {0: "YOU MUST REQUEST AT LEAST 1 KEY. CHANGE & RE-REQUEST."},
		111: {0: "INVALID PMS INTERFACE RESPONSE (21 OR 22). CONTACT PMS COMPANY."},
		112: {0: "SAFLOK INTERFACE COULDN'T ACCEPT ANOTHER REQUEST. RE-REQUEST IF DESIRED."},
		113: {0: "PMS INTERFACE LOST YOUR LAST REQUEST. RE-REQUEST IF DESIRED."},
		114: {0: "ENCODER HAD A PROBLEM DURING KEY-MAKING. RE-REQUEST IF DESIRED."},
		115: {0: "SAFLOK TIMED OUT YOUR REQUEST - GENERAL COMMUNICATIONS TIME OUT OCCURRED."},
		116: {0: "ENCODER SELECTED HAS A PROBLEM. RE-REQUEST OR SELECT ANOTHER ENCODER."},
		117: {0: "YOU DID NOT OVERRIDE ERROR. REQUEST IS TERMINATED."},
		118: {0: "INCOMPATIBLE SAFLOK & PMS INTERFACE SOFTWARE. CONTACT SAFLOK & PMS COMPANY."},
		119: {0: "KEY # nnnnn, LV yy IS A BATCH KEY. USE SAFLOK TERMINAL OR CONTACT SAFLOK."},
		120: {0: "KEY # nnnnn, LV yy IS A FAILSAFE KEY. USE SAFLOK TERMINAL OR CONTACT SAFLOK."},
		121: {0: "SAFLOK LOST YOUR REQUEST. RE-REQUEST IF DESIRED."},
		122: {0: "PMS SENT PFC 22 OR 21 WHEN SAFLOK DID NOT EXPECT EITHER. CONTACT PMS."},
		123: {0: "SAFLOK SENT STANDARD GRC BUT PMS INDICATED INVALID GRC CODE. CONTACT PMS."},
		124: {0: "PMS INTERFACE USED AN INVALID PASS OPTION > 1. CONTACT PMS."},
		125: {0: "PMS INTERFACE USED AN INVALID PASS #=0 OR >12.CONTACT PMS."},
		126: {0: "PMS INTERFACE USED AN INVALID # OF SECONDS. CONTACT PMS."},
		127: {0: "PMS INTERFACE USED INCORRECT DESTINATION STATION #. CONTACT PMS COMPANY."},
		128: {0: "PMS INTERFACE USED NON-NUMERIC CHARS FOR NUMERIC FIELD. CONTACT PMS COMPANY."},
		132: {0: "SAFLOK ERROR NOT HANDLED PROPERLY. CONTACT SAFLOK."},
		133: {0: "TIMED OUT WAITING FOR ENI BUFFER TO PMS INTERFACE."},
		134: {0: "TIMED OUT WAITING FOR SAFLOK COMPUTER TO ACCEPT REQUEST."},
		148: {0: "LOCK mmmmm FOR KEY # nnnnn, LV yy IS INACCESSIBLE. RESTORE ACCESS (TX 57) 1ST."},
		149: {0: "KEY # nnnnn, LV yy IS INACCESSABLE. MUST RESTORE TO ACCESS 1ST (TX 25)."},
		161: {0: "ENCODER xx IS NOT ON LINE OR DOES NOT EXIST. USE DIFFERENT ENCODER."},
		162: {0: "ENCODER xx IS NOT RESPONDING. CONTACT SAFLOK. USE DIFFERENT ENCODER"},
		163: {0: "STATION xx IS NOT AN ENCODER. USE DIFFERENT ENCODER."},
		189: {0: "ORIGINAL REQUEST WAS ABORTED PER ABORT MESSAGE."},
		190: {0: "ENCODER xx TIMED-OUT WAITING FOR KEY TO BE INSERTED. RE-TRY IF DESIRED."},
		192: {0: "ENCODER xx HAS A JAMMED KEY INSIDE. PRESS RUN MOTOR SWITCH FIRST."},
		193: {0: "KEY WAS REJECTED. KEY MUST BE FACE UP & POINTING IN. RE-TRY IF DESIRED."},
		194: {0: "KEY WAS REJECTED & MAY BE DAMAGED. USE A DIFFERENT KEY & RE-TRY IF DESIRED."},
		197: {0: "STATION xx HAS A BAD ROM. CONTACT SAFLOK. USE DIFFERENT ENCODER."},
		198: {0: "STATION xx IS BUSY WITH ANOTHER REQUEST. USE DIFFERENT ENCODER."},
		199: {0: "ENCODER DID NOT RESPOND. CHECK IT FOR PROBLEMS. RE-TRY IF DESIRED."},
		200: {0: "NO PREREG KEY # nnnnn, LV yy EXISTS. TRY ANOTHER KEY OR MAKE NEW KEYS."},
		201: {0: "KEY # nnnnn, LV yy IS INHIBITED. REPLACE ALL GUEST KEYS WITH NEW KEYS."},
		202: {0: "KEY # nnnnn, LV yy IS NOT PROGRAMMED IN LOCKS. REPROGRAM LOCK 1ST."},
		204: {0: "KEY # nnnnn, LV yy IS NOT PROGRAMMED IN LOCKS. REPROGRAM LOCK 1ST."},
		205: {
			1: "OCCUPIED W/ KEY # nnnnn, LV yy CHECKOUT NOT DUE mm/dd/yy. MUST CHECK OUT 1ST.",
			3: "KEY # nnnnn, LV yy MAY BE OUT OF SEQUENCE. REPLACE ALL KEYS WITH NEW"},
		206: {
			1: "OCCUPIED W/ KEY # nnnnn, LV yy CHECKOUT OVERDUE mm/dd/yy. MUST CHECK OUT 1ST.",
			3: "REPLACE ALL KEYS # nnnnn, LV yy WITH NEW KEYS."},
		207: {0: "MAKE DUPLICATE KEYS OR WAIT UNTIL mm/dd/yy hh:mm TO MAKE NEW KEYS."},
		208: {
			1: "CHECK IN PRE-REG EARLY DUE mm/dd/yy (KEY # nnnnn LV yy, TX 18) OR CANCEL.",
			3: "TOO LONG SINCE LAST NEW KEY # nnnnn, LV yy MADE mm/dd/yy. REPLACE KEYS WITH NEW."},
		209: {0: "CANCEL PRE-REG DUE mm/dd/yy (KEY # nnnnn LV yy) OR WAIT."},
		210: {
			1: "CHECK IN PRE-REG DUE mm/dd/yy (KEY # nnnnn LV yy, TX 18) OR CANCEL.",
			3: "NOT THE CURRENT GUEST KEY. RE-REQUEST KEY # nnnnn, LV yy OR MAKE NEW KEYS."},
		211: {
			1: "CHECKOUT mm/dd/yy hh:mm HAS ALREADY PASSED. CHANGE CHECKOUT 1ST.",
			3: "FOR CURRENT GUEST KEY, REQUEST KEY # nnnnn, LV yy OR MAKE NEW KEYS."},
		212: {
			1: "KEY EXPIRATION mm/dd/yy hh:mm IS BEFORE CHECKOUT. CHANGE EXPIRATION.",
			3: "KEY # nnnnn, LV yy IS DUE FOR OR CHECKED OUT. CHANGE CHECKOUT OR MAKE NEW."},
		213: {
			1: "KEY EXPIRATION mm/dd/yy hh:mm HAS ALREADY PASSED. CHANGE EXPIRATION.",
			3: "KEY # nnnnn, LV yy IS DUE FOR OR CHECKED OUT. CHANGE CHECKOUT OR MAKE NEW."},
		214: {0: "KEY EXPIRATION mm/dd/yy CAN'T BE 9 YEARS FROM NOW. CHANGE EXPIRATION."},
		215: {
			1: "CHANGE CHECKOUT BEFORE mm/dd/yy OR CHANGE PRE-REG KEY # nnnnn LV yy CHECKIN.",
			3: "KEY EXPIRATION mm/dd/yy SHIFT hh:mm HAS ALREADY PASSED. CHANGE EXPIARTION."},
		216: {
			1: "CHANGE CHECKOUT BEFORE mm/dd/yy hh:mm & RE-REQUEST.",
			3: "KEY # nnnnn, LV yy HAS MAX 255 DUPLICATE KEYS. REPLACE ALL KEYS WITH NEW."},
		217: {
			1: "PASS # yy MUST BE SELECTED. CONTACT PMS COMPANY OR ENTER Y.",
			3: "KEY EXPIRATION mm/dd/yy hh:mm IS BEFORE CHECKOUT. CHANGE EXPIRATION."},
		218: {
			1: "PASS # yy IS NOT A VALID PASS #. CONTACT PMS COMPANY OR ENTER N.",
			3: "KEY EXPIRATION mm/dd/yy hh:mm HAS ALREADY PASSED. CHANGE EXPIRATION."},
		219: {0: "KEY EXPIRATION mm/dd/yy CAN'T BE 9 YEARS FROM NOW. CHANGE EXPIRATION."},
		220: {0: "KEY EXPIRATION mm/dd/yy SHIFT hh:mm HAS ALREADY PASSED. CHANGE EXPIRATION."},
		221: {0: "PASS # yy MUST BE SELECTED. CONTACT PMS COMPANY OR ENTER Y."},
		222: {0: "PASS # yy IS NOT A VALID PASS #. CONTACT PMS COMPANY OR ENTER N"},
		223: {
			1: "PREREG KEY # nnnnn, LV yy WAS CHECKED IN mm/dd/yy. MUST USE IT OR CHECK OUT 1ST.",
			3: "USE SAFLOK TERMINAL TO MAKE KEY # nnnnn, LV yy."},
		224: {
			1: "PREREG KEY # nnnnn, LV yy WAS CHECKED IN mm/dd/yy. MUST USE IT OR CHECK OUT 1ST.",
			3: "KEY # nnnnn, LV yy IS DUE FOR OR CHECKED OUT. PREREG KEY EXISTS. VERIFY KEY."},
		225: {
			1: "OCCUPIED W/ KEY # nnnnn, LV yy CHECKOUT NOT DUE mm/dd/yy. MUST CHECK OUT 1ST.",
			3: "VERIFY GUEST KEY OR CHANGE CHECKOUT OF KEY # nnnnn, LV yy."},
		226: {0: "OCCUPIED W/ KEY # nnnnn, LV yy CHECKOUT OVERDUE mm/dd/yy. MUST CHECK OUT 1ST."},
		227: {0: "NEW KEYS WERE RECENTLY MADE mm/dd/yy hh:mm SO A NEW SEQUENCE CAN'T BE MADE YET."},
		228: {
			1: "LAST KEY DATE mm/dd/yy hh:mm IS AHEAD OF SYSTEM TIME. USE SAFLOK TO MAKE KEY.",
			3: "NEW KEY DATE mm/dd/yy hh:mm IS AHEAD OF SYSTEM. REPROGRAM LOCK 1ST."},
		229: {0: "REPROGRAM LOCK THEN REPLACE KEYS WITH NEW KEYS.."},
		230: {
			1: "PREREG KEY CHECKED IN EARLY. USE IT, WAIT UNTIL mm/dd/yy hh:mm OR USE SAFLOK.",
			3: "USE SAFLOK & VERIFY GUEST'S KEY BEFORE CONTINUING."},
		231: {0: "USE SAFLOK & VERIFY GUEST'S KEY BEFORE CONTINUING."},
	}

	grc04 = map[int]map[int]string{
		159: {0: "SAFLOK MAIN COMPUTER IS NOT POLLING ENI."},
		160: {0: "SAFLOK ENI OR MAIN COMPUTER IS NOT ON LINE."},
		164: {0: "SAFLOK KEY DATA FILES ARE CORRUPT. CONTACT SAFLOK."},
		165: {0: "SAFLOK MAIN COMPUTER STATION ERROR RESPONSE. NOTIFY SAFLOK."},
		166: {0: "SAFLOK INTERFACE IS BUSY SIGNING ON. RE-TRY LATER."},
		168: {0: "SAFLOK INTERFACE IS BUSY CLEARING REQUESTS DUE TO UNLINK. RE-REQUEST IF DESIRED"},
		170: {0: "SAFLOK MAIN COMPUTER CALLED INVALID PROGRAM ROUTINE. NOTIFY SAFLOK."},
		171: {0: "SAFLOK COMPUTER COULDN'T ACCEPT ANOTHER REQUEST. RE-REQUEST IF DESIRED."},
		173: {0: "SAFLOK COMPUTER DRIVE ACCESS PROBLEM. NOTIFY SAFLOK."},
		175: {0: "SAFLOK SYSTEM CAUSED TIME OUT ON YOUR RE-QUEST. RE-REQUEST IF DESIRED."},
		176: {0: "SAFLOK TX FILE DELETION PROBLEM. NOTIFY SAFLOK."},
		177: {0: "SAFLOK TX FILE IS CORRUPT. NOTIFY SAFLOK."},
		180: {0: "SAFLOK COMPUTER RAM SPACE PROBLEM. RE-REQUEST IF DESIRED."},
		181: {0: "SAFLOK COMPUTER CLOCK HARDWARE PROBLEM. NOTIFY SAFLOK."},
		182: {0: "SAFLOK CALCUALTION OVERFLOW. NOTIFY SAFLOK."},
		183: {0: "SAFLOK SYSTEM HAS READ BEYOND END OF FILE PROBLEM. CONTACT SAFLOK."},
		184: {0: "SAFLOK COMPUTER OUT OF DISK SPACE. NOTIFY SAFLOK."},
		185: {0: "SAFLOK COMPUTER FILE WRITE ERROR. NOTIFY SAFLOK."},
		187: {0: "SAFLOK SYSTEM HAS A FILE NOT FOUND PROBLEM. CONTACT SAFLOK."},
		188: {0: "SAFLOK CAN'T OPEN A FILE. NOTIFY SAFLOK."},
	}

	grc05 = map[int]map[int]string{
		254: {15: "KEYS ARE CHECKED OUT BUT WILL WORK UNTIL mm/dd/yy hh:mm OR UNTIL INHIBITED."},
		255: {15: "KEYS ARE CHECKED OUT AND ARE EXPIRED IN LOCKS."},
	}
)

// GetAnswerText returns a clear text for the response code by group and txc
func (d *Dispatcher) GetAnswerText(grc int, responseCode int, txc int) string {

	var errMsg map[int]string
	var exist bool

	switch grc {

	case 0: // success
		return ""

	case 3:
		errMsg, exist = grc03[responseCode]
		if !exist && responseCode > 231 {
			return fmt.Sprintf("REQUEST ABORTED (error code: %d, txc: %d)", responseCode, txc)
		}

	case 4:
		errMsg, exist = grc04[responseCode]
		if !exist && responseCode > 188 {
			return fmt.Sprintf("REQUEST ABORTED (error code: %d, txc: %d)", responseCode, txc)
		}

	case 5:
		errMsg, exist = grc05[responseCode]

	default:
		return fmt.Sprintf("unknown error code: %d, txc: %d, grc: %d", responseCode, txc, grc)
	}

	if !exist {
		return fmt.Sprintf("unknown error code: %d, txc: %d", responseCode, txc)
	}

	text, exist := errMsg[txc]
	if !exist {
		text, _ = errMsg[0]
	}

	if len(text) == 0 {
		return fmt.Sprintf("unknown error code: %d, txc: %d", responseCode, txc)
	}

	return text
}
